[programs.localnet]
mygifportal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
mygifportal = "494g856aNoMPdqu4n6KMwmLKfPTfxn3FtMwVqhZrvHuC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/zhanny/.config/solana/id.json"

[scripts]
test = "node tests/mygifportal.js"
